RTC_NXP_Arduino: SPI_for_RTC Class Reference
SPI_for_RTC Class Reference
#include <RTC_NXP.h>
Public Member Functions
void txrx (uint8_t *data, int size)
void reg_w (uint8_t reg_adr, uint8_t *data, int size)
void reg_w (uint8_t reg_adr, uint8_t data)
void reg_r (uint8_t reg_adr, uint8_t *data, int size)
uint8_t reg_r (uint8_t reg_adr)
void write_r8 (uint8_t reg, uint8_t val)
uint8_t read_r8 (uint8_t reg)
void bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
Detailed Description
SPI_for_RTC class
SPI interface operation for RTC devices
Definition at line 302 of file RTC_NXP.h.
Member Function Documentation
bit_op8()
void SPI_for_RTC::bit_op8 (uint8_t reg, uint8_t mask, uint8_t value)
Register overwriting with bit-mask
Register can be updated by bit level
Parameters
reg register index/address/pointer
mask bit-mask to protect overwriting
value value to overwrite
Definition at line 59 of file SPI_for_RTC.cpp.
read_r8()
uint8_t SPI_for_RTC::read_r8 (uint8_t reg)
Register read, 8 bit
Parameters
reg register index/address/pointer
Returns
data value
Definition at line 54 of file SPI_for_RTC.cpp.
reg_r() [1/2]
uint8_t SPI_for_RTC::reg_r (uint8_t reg_adr)
Single register read
Parameters
reg register index/address/pointer
Returns
read data
Definition at line 40 of file SPI_for_RTC.cpp.
reg_r() [2/2]
void SPI_for_RTC::reg_r (uint8_t reg_adr, uint8_t * data, int size)
Multiple register read
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Definition at line 27 of file SPI_for_RTC.cpp.
Referenced by bit_op8(), and read_r8().
reg_w() [1/2]
void SPI_for_RTC::reg_w (uint8_t reg_adr, uint8_t * data, int size)
Multiple register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Definition at line 10 of file SPI_for_RTC.cpp.
Referenced by bit_op8(), and write_r8().
reg_w() [2/2]
void SPI_for_RTC::reg_w (uint8_t reg_adr, uint8_t data)
Single register write
Parameters
reg register index/address/pointer
data pointer to data buffer
size data size
Returns
transferred data size
Definition at line 20 of file SPI_for_RTC.cpp.
txrx()
void SPI_for_RTC::txrx (uint8_t * data, int size)
Send data
Parameters
data pointer to data buffer
size data size
stop option: generating STOP-condition after transaction. Defailt: true
Returns
transferred data size
Definition at line 3 of file SPI_for_RTC.cpp.
Referenced by reg_r(), and reg_w().
write_r8()
void SPI_for_RTC::write_r8 (uint8_t reg, uint8_t val)
Register write, 8 bit
Parameters
reg register index/address/pointer
val data value
Definition at line 49 of file SPI_for_RTC.cpp.
The documentation for this class was generated from the following files:
RTC_NXP.h
SPI_for_RTC.cpp